# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShapefileLoader
                                 A QGIS plugin
 This plugin will load shapefiles from your PC and open then in your QGis desktop application
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-16
        copyright            : (C) Odhis
        email                : odhiambokevine.o@gmail.com
        git source           : https://github.com/odhiambo-web/Group6.git
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShapefileLoader class from file ShapefileLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shapefile_loader import ShapefileLoader
    return ShapefileLoader(iface)
